// Generated by CoffeeScript 1.3.3
var diff, htmlDiff, stringDiff;

diff = function(before, after) {
  var i, j, k, lastRow, ohash, subLength, subStartAfter, subStartBefore, thisRow, val, _i, _j, _k, _len, _len1, _len2, _ref, _ref1;
  ohash = {};
  for (i = _i = 0, _len = before.length; _i < _len; i = ++_i) {
    val = before[i];
    if (!(val in ohash)) {
      ohash[val] = [];
    }
    ohash[val].push(i);
  }
  lastRow = (function() {
    var _j, _ref, _results;
    _results = [];
    for (i = _j = 0, _ref = before.length; 0 <= _ref ? _j < _ref : _j > _ref; i = 0 <= _ref ? ++_j : --_j) {
      _results.push(0);
    }
    return _results;
  })();
  subStartBefore = subStartAfter = subLength = 0;
  for (j = _j = 0, _len1 = after.length; _j < _len1; j = ++_j) {
    val = after[j];
    thisRow = (function() {
      var _k, _ref, _results;
      _results = [];
      for (i = _k = 0, _ref = before.length; 0 <= _ref ? _k < _ref : _k > _ref; i = 0 <= _ref ? ++_k : --_k) {
        _results.push(0);
      }
      return _results;
    })();
    _ref1 = (_ref = ohash[val]) != null ? _ref : [];
    for (_k = 0, _len2 = _ref1.length; _k < _len2; _k++) {
      k = _ref1[_k];
      thisRow[k] = (k && lastRow[k - 1] ? 1 : 0) + 1;
      if (thisRow[k] > subLength) {
        subLength = thisRow[k];
        subStartBefore = k - subLength + 1;
        subStartAfter = j - subLength + 1;
      }
    }
    lastRow = thisRow;
  }
  if (subLength === 0) {
    return [].concat((before.length ? [['-', before]] : []), (after.length ? [['+', after]] : []));
  } else {
    return [].concat(diff(before.slice(0, subStartBefore), after.slice(0, subStartAfter)), [['=', after.slice(subStartAfter, subStartAfter + subLength)]], diff(before.slice(subStartBefore + subLength), after.slice(subStartAfter + subLength)));
  }
};

stringDiff = function(before, after) {
  return diff(before.split(/[ ]+/), after.split(/[ ]+/));
};

htmlDiff = function(before, after) {
  var a, b, con;
  con = {
    '=': (function(x) {
      return x;
    }),
    '+': (function(x) {
      return '<ins>' + x + '</ins>';
    }),
    '-': (function(x) {
      return '<del>' + x + '</del>';
    })
  };
  return ((function() {
    var _i, _len, _ref, _ref1, _results;
    _ref = stringDiff(before, after);
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      _ref1 = _ref[_i], a = _ref1[0], b = _ref1[1];
      _results.push(con[a](b.join(' ')));
    }
    return _results;
  })()).join(' ');
};
